// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var i, j, k;
    for (i = j = 1; j <= 20; i = ++j) {
      $('#turn').append($('<option>').attr('value', i).html(i));
    }
    for (i = k = 1; k <= 20; i = ++k) {
      $('#tate, #yoko').append($('<option>').attr('value', i).html(i));
    }
    $('#tate, #yoko').on('change', boardRedraw);
    $('#tate').val(5);
    $('#yoko').val(5);
    boardRedraw();
    $('body').on('mousemove', function(e) {
      window.isMouseDown = e.buttons === 1;
      return e.preventDefault();
    });
    return $('#calc').on('click', function() {
      var b, color, index, l, path, ref, ref1, res, results, td, turn, x, y;
      window.count = 0;
      $('#board td').html('');
      b = getBoard();
      turn = Number($('#turn').val());
      res = Kami.solve(b, turn);
      if (res === false) {
        $('#message').html('NO ANSWER');
      } else {
        $('#message').html('');
        results = [];
        for (index = l = 0, ref = res.length; 0 <= ref ? l < ref : l > ref; index = 0 <= ref ? ++l : --l) {
          ref1 = res[index], color = ref1[0], path = ref1[1];
          x = path[0], y = path[1];
          td = $('#board tr').eq(x).children('td').eq(y);
          results.push($(td).html($(td).html() + '<br>[' + (index + 1) + ']' + color));
        }
        return results;
      }
    });
  });

  window.isMouseDown = false;

  window.count = 0;

  window.boardRedraw = function() {
    var j, k, ref, ref1, t, tate, tr, y, yoko;
    $('#board').empty();
    tate = Number($('#tate').val());
    yoko = Number($('#yoko').val());
    for (t = j = 0, ref = tate; 0 <= ref ? j < ref : j > ref; t = 0 <= ref ? ++j : --j) {
      tr = $('<tr>');
      for (y = k = 0, ref1 = yoko; 0 <= ref1 ? k < ref1 : k > ref1; y = 0 <= ref1 ? ++k : --k) {
        tr.append($('<td>').addClass('colora cell center').attr('value', 'a'));
      }
      $('#board').append(tr);
    }
    return $('#board td').on('mouseover', function(e) {
      var value;
      if (!window.isMouseDown) {
        return;
      }
      value = $("input[name='color']:checked").val();
      $(this).attr('value', value);
      $(this).removeClass('colora colorb colorc colord colore colorf');
      return $(this).addClass('color' + value);
    });
  };

  window.getBoard = function() {
    var j, k, len, len1, td, tds, tr, trs, x, y;
    x = [];
    trs = $('#board tr');
    for (j = 0, len = trs.length; j < len; j++) {
      tr = trs[j];
      y = [];
      tds = $(tr).children('td');
      for (k = 0, len1 = tds.length; k < len1; k++) {
        td = tds[k];
        y.push($(td).attr('value'));
      }
      x.push(y);
    }
    return x;
  };

}).call(this);
